[versions]
agp = "8.2.2"
kotlin = "1.9.22"
composeBom = "2024.03.00"
coroutines = "1.7.3"
hilt = "2.50"
room = "2.6.1"
work = "2.9.0"
datastore = "1.0.0"
lifecycle = "2.6.2"
navigationCompose = "2.7.6"
ktlint = "11.6.1"
androidxJunit = "1.1.5"
espresso = "3.5.1"
junit = "4.13.2"
activityCompose = "1.8.2"
glance = "1.0.0"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version = "1.12.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
material = { module = "com.google.android.material:material", version = "1.11.0" }
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeRuntime = { module = "androidx.compose.runtime:runtime" }
composeUi = { module = "androidx.compose.ui:ui" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeFoundation = { module = "androidx.compose.foundation:foundation" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
composeLifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hiltNavigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.1.0" }
workRuntime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
workHilt = { module = "androidx.hilt:hilt-work", version = "1.1.0" }
workCompiler = { module = "androidx.hilt:hilt-compiler", version = "1.1.0" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
datastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
glanceAppWidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
glanceMaterial3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
