[versions]
junit = "4.13.2"
androidxJunit = "1.1.5"
espresso = "3.5.1"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
composeUiTest = { module = "androidx.compose.ui:ui-test-junit4" }
composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
truth = { module = "com.google.truth:truth", version = "1.1.5" }
